# Generated by Django 2.2 on 2022-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0021_remove_preference_item_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_id',
            field=models.CharField(help_text='The CLIENT_ID given by MercadoPago.  This is called APP_ID by MercadoLibre.', max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='secret_key',
            field=models.CharField(help_text='The CLIENT_SECRET given by MercadoPago. This is called SECRET_KEY by MercadoLibre.', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_detail',
            field=models.CharField(max_length=250, verbose_name='status detail'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='mp_id',
            field=models.CharField(help_text='The id MercadoPago has assigned for this Preference', max_length=250, null=True, verbose_name='mercadopago id'),
        ),
    ]
